"""empty message

Revision ID: 0c170500fd72
Revises: e14ed9a89055
Create Date: 2024-10-08 20:39:14.613469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c170500fd72'
down_revision = 'e14ed9a89055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('user_input_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('user_input_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
