"""123

Revision ID: b42ff25560ab
Revises: f186a501ec14
Create Date: 2024-10-11 01:23:06.502107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42ff25560ab'
down_revision = 'f186a501ec14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_phone_number', sa.String(length=15), nullable=False),
    sa.Column('user_input_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_input_id'], ['user_input.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
