"""empty message

Revision ID: e14ed9a89055
Revises: 
Create Date: 2024-10-08 20:20:28.439275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14ed9a89055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone_number', sa.String(length=15), nullable=False))
        # Provide a name for the unique constraint
        batch_op.create_unique_constraint('uq_user_phone_number', ['user_phone_number'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_phoneNumber')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phoneNumber', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        # Specify the correct name of the unique constraint to drop
        batch_op.drop_constraint('uq_user_phone_number', type_='unique')
        batch_op.drop_column('user_phone_number')

    # ### end Alembic commands ###
